"""empty message

Revision ID: 143fc67eb0cd
Revises: 
Create Date: 2020-06-22 17:48:47.933714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143fc67eb0cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('watched_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'watched_date')
    op.drop_column('review', 'published_date')
    # ### end Alembic commands ###
