"""empty message

Revision ID: 4c4bd1a6d960
Revises: 
Create Date: 2021-09-22 22:09:06.744337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4bd1a6d960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_show',
    sa.Column('show_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_link', sa.Text(), nullable=True),
    sa.Column('movie_link', sa.Text(), nullable=True),
    sa.Column('banner_image_link', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('watched_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warsaw_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('podcast_episode',
    sa.Column('episode_id', sa.Text(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('show_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['podcast_show.show_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast_episode')
    op.drop_table('warsaw_user')
    op.drop_table('revoked_token')
    op.drop_table('review')
    op.drop_table('podcast_show')
    # ### end Alembic commands ###
