"""empty message

Revision ID: 146b422e81af
Revises: 
Create Date: 2020-11-29 18:32:05.122171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146b422e81af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_show',
    sa.Column('show_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('podcast_episode',
    sa.Column('episode_id', sa.Text(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('show_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['podcast_show.show_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast_episode')
    op.drop_table('podcast_show')
    # ### end Alembic commands ###
